
USE DB_SQL_GAMMA;

CREATE TABLE REGIAO
(
    ID 					INT				NOT NULL IDENTITY(1, 1),
	NOME				VARCHAR(50)		NOT NULL,
	SIGLA				VARCHAR(2)		NOT NULL,
	CONSTRAINT PK_REGIAO PRIMARY KEY (ID)
);

CREATE TABLE UF
(
    ID 					INT				NOT NULL IDENTITY(1, 1),
	ID_REGIAO			INT				NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	SIGLA				VARCHAR(2)		NOT NULL,
	CONSTRAINT PK_UF PRIMARY KEY (ID),
	CONSTRAINT FK_UF_REGIAO FOREIGN KEY (ID_REGIAO)
		REFERENCES REGIAO (ID)
);


CREATE TABLE CIDADE
(
    ID 					INT				NOT NULL IDENTITY(1, 1),
    ID_UF				INT				NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	N_IBGE				VARCHAR(8)		NOT NULL,
	CONSTRAINT PK_CIDADE PRIMARY KEY (ID),
	CONSTRAINT FK_CIDADE_UF FOREIGN KEY (ID_UF)
		REFERENCES UF (ID)	
);

CREATE TABLE DISTRITO
(
    ID 					INT				NOT NULL IDENTITY(1, 1),
    ID_CIDADE			INT				NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	CONSTRAINT PK_DISTRITO PRIMARY KEY (ID),
	CONSTRAINT FK_DISTRITO_CIDADE FOREIGN KEY (ID_CIDADE)
		REFERENCES CIDADE (ID)	
);
SELECT * FROM DISTRITO;

