CREATE DATABASE DB_FINANCEIRO;

USE DB_FINANCEIRO;

CREATE TABLE DADOS_FATURAMENTO
(
	ID				INT				NOT NULL IDENTITY(1, 1),
	COD_ORCAMENTO	VARCHAR(4)		NULL,
	COD_PROJETO		VARCHAR(4)		NULL,
	FATURAMENTO		DECIMAL(10, 2)	NULL,
	DATA			DATETIME		NULL,
	CONSTRAINT PK_DADOS_FATURAMENTO PRIMARY KEY (ID)
);

CREATE TABLE LOG
(
	ID				INT			NOT NULL IDENTITY(1, 1),
	DATA			DATETIME	NOT NULL,
	DESCRICAO		TEXT		NOT NULL,
	CONSTRAINT PK_LOG PRIMARY KEY (ID)
);

SELECT GETDATE()

-- DELETE FROM DADOS_FATURAMENTO;
-- DELETE FROM LOG;

SELECT * FROM DADOS_FATURAMENTO

SELECT * FROM LOG

